apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: deploy-openshift
spec:
  pipelineRef:
    name: deploy-openshift
  params:
    - name: cluster
      value: 'magic'
    - name: async
      value: 'false'
    - name: workers
      value: '2'
    - name: version
      value: 'nightly'
    - name: tag
      value: '4.10'
