apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: deploy-openshift
spec:
  pipelineRef:
    name: deploy-openshift
  params:
    - name: cluster
      value: "newyear"
    - name: async
      value: "false"
